export const ADD_FEEDBACK_QUESTION_START =
  "ADD_FEEDBACK_QUESTION_START"
export const ADD_FEEDBACK_QUESTION_SUCCESS =
  "ADD_FEEDBACK_QUESTION_SUCCESS"
export const ADD_FEEDBACK_QUESTION_FAILED =
  "ADD_FEEDBACK_QUESTION_FAILED"
