export const DEACTIVATE_ACCEPT_START =
  "DEACTIVATE_ACCEPT_START"
export const DEACTIVATE_ACCEPT_SUCCESS =
  "DEACTIVATE_ACCEPT_SUCCESS"
export const DEACTIVATE_ACCEPT_FAILED =
  "DEACTIVATE_ACCEPT_FAILED"
