export const FETCH_ALL_DOCUMENT_NEED_START = "FETCH_ALL_DOCUMENT_NEED_START"
export const FETCH_ALL_DOCUMENT_NEED_SUCCESS = "FETCH_ALL_DOCUMENT_NEED_SUCCESS"
export const FETCH_ALL_DOCUMENT_NEED_FAILED = "FETCH_ALL_DOCUMENT_NEED_FAILED"

export const FETCH_ALL_OTHER_STATUS_START = "FETCH_ALL_OTHER_STATUS_START"
export const FETCH_ALL_OTHER_STATUS_SUCCESS = "FETCH_ALL_OTHER_STATUS_SUCCESS"
export const FETCH_ALL_OTHER_STATUS_FAILED = "FETCH_ALL_OTHER_STATUS_FAILED"



