export const FETCH_DISPUTED_TRANSACTIONS_START =
  "FETCH_DISPUTED_TRANSACTIONS_START"
export const FETCH_DISPUTED_TRANSACTIONS_SUCCESS =
  "FETCH_DISPUTED_TRANSACTIONS_SUCCESS"
export const FETCH_DISPUTED_TRANSACTIONS_FAILED =
  "FETCH_DISPUTED_TRANSACTIONS_FAILED"
