//Get Adminlist
export const MEMBER_API_SUCCESS = "MEMBER_API_SUCCESS";
export const MEMBER_API_FAIL = "MEMBER_API_FAIL";
export const GET_MEMBER_DATA = "GET_MEMBER_DATA";

export const GET_ALL_COMPANY_LIST = "GET_ALL_COMPANY_LIST";
export const GET_ALL_COMPANY_LIST_FAIL = "GET_ALL_COMPANY_LIST_FAIL";
export const GET_ALL_COMPANY_LIST_SUCCESS = "GET_ALL_COMPANY_LIST_SUCCESS";
