export const FETCH_TOTAL_TRANS_START = "FETCH_TOTAL_TRANS_START"
export const FETCH_TOTAL_TRANS_SUCCESS = "FETCH_TOTAL_TRANS_SUCCESS"
export const FETCH_TOTAL_TRANS_FAILED = "FETCH_TOTAL_TRANS_FAILED"



