export const USER_ACTIVE_DEACTIVATE_START =
  "USER_ACTIVE_DEACTIVATE_START"
export const USER_ACTIVE_DEACTIVATE_SUCCESS =
  "USER_ACTIVE_DEACTIVATE_SUCCESS"
export const USER_ACTIVE_DEACTIVATE_FAILED =
  "USER_ACTIVE_DEACTIVATE_FAILED"
