export const FETCH_LATEST_TRANS_START = "FETCH_LATEST_TRANS_START"
export const FETCH_LATEST_TRANS_SUCCESS = "FETCH_LATEST_TRANS_SUCCESS"
export const FETCH_LATEST_TRANS_FAILED = "FETCH_LATEST_TRANS_FAILED"


export const APPROVE_REJECT_LATEST_TRANSACTION = "APPROVE_REJECT_LATEST_TRANSACTION"
export const APPROVE_REJECT_LATEST_TRANSACTION_SUCCESS = "APPROVE_REJECT_LATEST_TRANSACTION_SUCCESS"
export const APPROVE_REJECT_LATEST_TRANSACTION_FAIL = "APPROVE_REJECT_LATEST_TRANSACTION_FAIL"

export const ESCLATET_TRANSACTION = "ESCLATET_TRANSACTION"
export const ESCLATET_TRANSACTION_SUCCESS = "ESCLATET_TRANSACTION_SUCCESS"
export const ESCLATET_TRANSACTION_FAIL = "ESCLATET_TRANSACTION_FAIL"

export const REQ_FOR_ADDITIONAL_DOC = "REQ_FOR_ADDITIONAL_DOC"
export const REQ_FOR_ADDITIONAL_DOC_SUCCESS = "REQ_FOR_ADDITIONAL_DOC_SUCCESS"
export const REQ_FOR_ADDITIONAL_DOC_FAIL = "REQ_FOR_ADDITIONAL_DOC_FAIL"


export const SUBSCRIBE_PACKAGE = "SUBSCRIBE_PACKAGE"
export const SUBSCRIBE_PACKAGE_SUCCESS = "SUBSCRIBE_PACKAGE_SUCCESS"
export const SUBSCRIBE_PACKAGE_FAIL = "SUBSCRIBE_PACKAGE_FAIL"


export const GET_SUBSCRIBE_PACKAGE = "GET_SUBSCRIBE_PACKAGE"
export const GET_SUBSCRIBE_PACKAGE_SUCCESS = "GET_SUBSCRIBE_PACKAGE_SUCCESS"
export const GET_SUBSCRIBE_PACKAGE_FAIL = "GET_SUBSCRIBE_PACKAGE_FAIL"

export const GET_ALL_PAYMENT_LOGS = "GET_ALL_PAYMENT_LOGS"
export const GET_ALL_PAYMENT_LOGS_SUCCESS = "GET_ALL_PAYMENT_LOGS_SUCCESS"
export const GET_ALL_PAYMENT_LOGS_FAIL = "GET_ALL_PAYMENT_LOGS_FAIL"


