export const FETCH_REQUEST_DEACTIVATE_START = "FETCH_REQUEST_DEACTIVATE_START"
export const FETCH_REQUEST_DEACTIVATE_SUCCESS = "FETCH_REQUEST_DEACTIVATE_SUCCESS"
export const FETCH_REQUEST_DEACTIVATE_FAILED = "FETCH_REQUEST_DEACTIVATE_FAILED"



