export const FETCH_APPROVED_TRANSACTIONS_START =
  "FETCH_APPROVED_TRANSACTIONS_START"
export const FETCH_APPROVED_TRANSACTIONS_SUCCESS =
  "FETCH_APPROVED_TRANSACTIONS_SUCCESS"
export const FETCH_APPROVED_TRANSACTIONS_FAILED =
  "FETCH_APPROVED_TRANSACTIONS_FAILED"

  export const GET_LATEST_TRANSACTIONS =
  "GET_LATEST_TRANSACTIONS"
export const GET_LATEST_TRANSACTIONS_SUCCESS =
  "GET_LATEST_TRANSACTIONS_SUCCESS"
export const GET_LATEST_TRANSACTIONS_FAILED =
  "GET_LATEST_TRANSACTIONS_FAILED"
