export const FETCH_REOPEN_TRANS_START = "FETCH_REOPEN_TRANS_START"
export const FETCH_REOPEN_TRANS_SUCCESS = "FETCH_REOPEN_TRANS_SUCCESS"
export const FETCH_REOPEN_TRANS_FAILED = "FETCH_REOPEN_TRANS_FAILED"



