export const FETCH_DASHBOARD_ADMIN_DATA_START =
  "FETCH_DASHBOARD_ADMIN_DATA_START"
export const FETCH_DASHBOARD_ADMIN_DATA_SUCCESS =
  "FETCH_DASHBOARD_ADMIN_DATA_SUCCESS"
export const FETCH_DASHBOARD_ADMIN_DATA_FAILED =
  "FETCH_DASHBOARD_ADMIN_DATA_FAILED"
