export const PROFILE_EDIT_ADMIN_START =
  "PROFILE_EDIT_ADMIN_START"
export const PROFILE_EDIT_ADMIN_SUCCESS =
  "PROFILE_EDIT_ADMIN_SUCCESS"
export const PROFILE_EDIT_ADMIN_FAILED =
  "PROFILE_EDIT_ADMIN_FAILED"
