export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"
export const FORGET_PASSWORD_WITH_TOKEN = "FORGET_PASSWORD_WITH_TOKEN"

export const CHANGE_PASSWORD_THROUGH_LINK = "CHANGE_PASSWORD_THROUGH_LINK"
export const CHANGE_PASSWORD_THROUGH_LINK_SUCCESS = "CHANGE_PASSWORD_THROUGH_LINK_SUCCESS"
export const CHANGE_PASSWORD_THROUGH_LINK_FAIL = "CHANGE_PASSWORD_THROUGH_LINK_FAIL"


